### ISSUE TITLE
First and Third Slide Deck Unavailable - Incorrect Name

### ISSUE THREAD

**Issue by julirosesim** [dkmcgrath/courses#11]
First and Third Slide Deck Unavailable - Incorrect Name
Lecture1.pdf instead of lecture1.pdf
lecture2a.pdf instead of lecture3.pdf

**Comment by dkmcgrath** [comment]
This should be fixed now.

**Comment by dkmcgrath** [comment]
Also, you're welcome to fix things. I give extra credit for pull requests which fix these sorts of errors.
